### PR TITLE
Issue 167: Allow long file names to be uploaded to S3

### LINKED ISSUE #167: Allow long file names to be uploaded to S3
# Task Description
Given a file with a long filename (around 200 characters) deeper in directories it uses the whole path as a file temporary name. Unfortunately, UNIX filesystems support only files up to 255 characters, so the upload will fail with exception `File name too long`. S3 systems support file names up to 1024 characters as can be seen [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) -  so there is no reason to not accept this file to upload.

# Tasks

The following tasks will need to be carried out:
* [ ] When creating a temp file in `S3SeekableByteChannel`, do not use the full depth of filename as a temporary name, but just the path file name.

# Useful Links

* [Upplication/Amazon-S3-FileSystem-NIO2#120](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/issues/120) : Allow longer file names to be upload to S3

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov

### PR DESCRIPTION
**Pull request by ptirador**
# Pull Request Description

This pull request closes #167.

# Acceptance Test

* [x] Building the code with `mvn clean install -Pintegration-tests` still works.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see [provide details here]
  * [x] No

### CODE REVIEW

File: src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java [hunk 1]
```diff
@@ -71,7 +71,7 @@ else if (!exists && !this.options.contains(StandardOpenOption.CREATE_NEW) && !th
 
         if(tempFileRequired)
         {
-            tempFile = Files.createTempFile("temp-s3-", key.replaceAll("/", "_"));
+            tempFile = Files.createTempFile("temp-s3-", fileName == null ? key : fileName.toString());
```
Comment (steve-todorov) [inline src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java:74]: Honestly, I would just leave this as:
```suggestion
            tempFile = Files.createTempFile("s3fs-");
```
simply because if the `fileName` is again, for some reason, larger than what UNIX can handle it would fail with the same exception, would it not?

Have you tried listing a "directory" which holds a file with very long name? Would this also throw an exception?

Comment (ptirador) [reply src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java]: You are absolutely right, the case that you are saying would also throw an exception.
I've just fixed it. 
BTW, `createTempFile` method also needs a suffix parameter, that's why I've added a `.tmp` extension.

Comment (steve-todorov) [reply src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java]: Awesome! What about the listing long file names - would that also throw an exception we should address in a follow-up?

File: src/test/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannelTest.java [hunk 2]
```diff
@@ -172,4 +172,31 @@ void tempFileDisappeared()
         assertNotNull(exception);
     }
 
+    @Test
+    void writeFileWithReallyLongName() throws IOException {
```
Comment (carlspring) [inline src/test/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannelTest.java:176]:
```suggestion
    void writeFileWithReallyLongName() throws IOException
    {
```

File: src/test/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannelTest.java [hunk 3]
```diff
@@ -172,4 +172,31 @@ void tempFileDisappeared()
...
+
+        //given
+        final S3ClientMock client = S3MockFactory.getS3ClientMock();
+        final String longDirectoryName = "FuscetellusodiodapibusidfermentumquissuscipitideratEtiamquisquamVestibulumeratnullaullamcorpernecrutrumnonnon";
+        final String longFileName = "ummyaceratSedutperspiciatisundeomnisisfasdfasdfasfsafdtenatuserrorsitvoluptatemaccusantiumdoloremquelaudantiumtotamremaperiameaqueipsaqummyaceratSedutperspiciatisundeomnisisfasdfasdfasfsafdtenatuserrorsitvoluptatemaccusantiumdoloremquelaudantiumtotamremaperiameaqueipsaq";
+        final String bucketName = "buck";
+        final String fileName = longDirectoryName + "/" + longFileName;
+        client.bucket(bucketName).file(fileName);
```
Comment (carlspring) [inline src/test/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannelTest.java:184]:
```suggestion
        final String fileName = longDirectoryName + "/" + longFileName;
        
        client.bucket(bucketName).file(fileName);
```

File: src/test/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannelTest.java [hunk 4]
```diff
@@ -172,4 +172,31 @@ void tempFileDisappeared()
...
+
+        final FileSystem fileSystem = FileSystems.getFileSystem(S3EndpointConstant.S3_GLOBAL_URI_TEST);
+        final String pathStr = String.format("/%s/%s", bucketName, fileName);
+        final S3Path file1 = (S3Path) fileSystem.getPath(pathStr);
+        final S3SeekableByteChannel channel = spy(
+                new S3SeekableByteChannel(file1, EnumSet.of(StandardOpenOption.WRITE), true));
```
Comment (carlspring) [inline src/test/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannelTest.java:190]:
```suggestion
        final S3SeekableByteChannel channel = spy(new S3SeekableByteChannel(file1, EnumSet.of(StandardOpenOption.WRITE), true));
```

File: src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java (hunk 1 above)
Comment (carlspring) [reply src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java]: We should probably check this as well, while we're at it (already).

Comment (ptirador) [reply src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java]: I'm not sure if I understand you... I've created a directory in my S3 bucket; there I've uploaded a file whose name has more than 255 characters, then I've listed the objects in the directory using the AWS SDK v2 API, and I can obtain it without any problem.

Comment (carlspring) [reply src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java]: Then, in this case, you seem to have covered this. Thanks! :)

**Review by carlspring — APPROVED** [review]
LGTM! Thank you very much! :)

**Comment by ptirador** [comment]
@carlspring: Since this is already reviewed, can it be merged?

**Review by steve-todorov — APPROVED** [review]
LGTM! Thanks for your work! :)

**Comment by carlspring** [comment]
Thanks, Pablo! :)
