### PR TITLE
Issue 99: Switch the NIO implementation to use AsynchronousFileChannel instead of FileChannel

### LINKED ISSUE #99: Switch the NIO implementation to use AsynchronousFileChannel instead of FileChannel
# Task Description
The AWS SDK for Java 2.x utilizes a new, non-blocking SDK architecture built on [Netty](https://netty.io/) to support true non-blocking I/O. Taking advantage of it, we can also switch the NIO implementation to use `AsynchronousFileChannel`. This should give a significant performance boost.

A plain `FileChannel` implements `InterruptibleChannel` so it, as well as anything that uses it such as the `OutputStream` returned by `Files.newOutputStream()`, has the unfortunate [[1]], [[2]] behaviour that performing any blocking operation on it (e.g. `read()` and `write()`) in a thread in interrupted state will cause the Channel itself to close with `java.nio.channels.ClosedByInterruptException`.

If this is a problem, using `AsynchronousFileChannel` instead is a possible alternative.

[1]: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6608965
[2]: https://bugs.openjdk.java.net/browse/JDK-4469683

# Tasks

The following tasks will need to be carried out:
* [ ] Make `S3FileChannel` extend `AsynchronousFileChannel` instead of `FileChannel` and override the respective methods associated to this new class. 
* [ ] Make `S3FileSystemProvider` override the method `newAsynchronousFileChannel` instead of `newFileChannel` from `FileSystemProvider`.

# Task Relationships

This task:
* Is a follow-up of: #63

# Useful Links

* [A Guide To NIO2 Asynchronous File Channel](https://www.baeldung.com/java-nio2-async-file-channel)
* [AsynchronousFileChannel Java API](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/AsynchronousFileChannel.html)

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov

### PR DESCRIPTION
**Pull request by ptirador**
# Pull Request Description

This pull request closes #99 .

# Acceptance Test

* [x] Building the code with `mvn clean install -Pintegration-tests` still works.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see [provide details here]
  * [x] No

### CODE REVIEW

**Comment by ptirador** [comment]
@carlspring: This is ready for review.

File: src/main/java/org/carlspring/cloud/storage/s3fs/S3FileChannel.java [hunk 1]
```diff
@@ -30,234 +37,428 @@
...
-                 !this.options.contains(StandardOpenOption.CREATE))
+        try
         {
-            throw new NoSuchFileException(format("target not exists: %s", path));
-        }
+            if (!isOpen())
+            {
+                if (exists && this.options.contains(StandardOpenOption.CREATE_NEW))
+                {
+                    throw new FileAlreadyExistsException(format("target already exists: %s", path));
```
Comment (carlspring) [inline src/main/java/org/carlspring/cloud/storage/s3fs/S3FileChannel.java:98]:
```suggestion
                    throw new FileAlreadyExistsException(format("Target already exists: %s", path));
```

File: src/main/java/org/carlspring/cloud/storage/s3fs/S3FileChannel.java [hunk 2]
```diff
@@ -30,234 +37,428 @@
...
+                }
+                else if (!exists && !this.options.contains(StandardOpenOption.CREATE_NEW) &&
+                         !this.options.contains(StandardOpenOption.CREATE))
+                {
+                    throw new NoSuchFileException(format("target not exists: %s", path));
```
Comment (carlspring) [inline src/main/java/org/carlspring/cloud/storage/s3fs/S3FileChannel.java:103]:
```suggestion
                    throw new NoSuchFileException(format("The target does not exist: %s", path));
```

File: src/test/java/org/carlspring/cloud/storage/s3fs/S3FileChannelTest.java [hunk 3]
```diff
@@ -39,6 +54,14 @@
 
     private final S3ClientMock client = S3MockFactory.getS3ClientMock();
 
+    private static Stream<Arguments> positionAndBytesReadForReadProvider()
+    {
+        return Stream.of(
+                Arguments.of(0, 10),
+                Arguments.of(5, 9),
+                Arguments.of(15, -1)
+        );
```
Comment (carlspring) [inline src/test/java/org/carlspring/cloud/storage/s3fs/S3FileChannelTest.java:63]:
```suggestion
        return Stream.of(Arguments.of(0, 10),
                         Arguments.of(5, 9),
                         Arguments.of(15, -1));
```

File: src/test/java/org/carlspring/cloud/storage/s3fs/S3FileChannelTest.java [hunk 4]
```diff
@@ -56,78 +81,310 @@ public void tearDown()
         s3fsProvider.close((S3FileSystem) fileSystem);
     }
 
+    @ParameterizedTest(name = "{index} ==> position={0}, bytesRead={1}")
+    @MethodSource(value = "positionAndBytesReadForReadProvider")
```
Comment (carlspring) [inline src/test/java/org/carlspring/cloud/storage/s3fs/S3FileChannelTest.java:85]: Does this make sense to be parameterized, if it's just for one value (or... am I misreading something)?

Comment (ptirador) [reply src/test/java/org/carlspring/cloud/storage/s3fs/S3FileChannelTest.java:83]: Yes, it does make sense because that's not just a value, that's the name of the method `positionAndBytesReadForReadProvider`, which provides multiple arguments for the test. Take it into account that this is using `@MethodSource` annotation instead of `@ValueSource` annotation.

Comment (carlspring) [reply src/test/java/org/carlspring/cloud/storage/s3fs/S3FileChannelTest.java:83]: Ah, right! I see, thanks for the clarification! :)

**Review by carlspring — APPROVED** [review]
LGTM! Thanks a lot! :)

**Comment by carlspring** [comment]
Thank you for this great pull request and, above all, thanks for adding so much documentation as well! :)
