### PR TITLE
Issue 146: Unable to change directories when exposed via Mina SFTP

### LINKED ISSUE #146: Unable to change directories when exposed via Mina SFTP
# Task Description
When using S3FS as a file system for Mina SFTP, it's not possible to change the directory (`cd` command):

```
sftp> ls -l
d---------   1 OWNER@   GROUP@          0 Jan 25 10:51 bar
d---------   1 OWNER@   GROUP@          0 Jan 25 10:42 foo
sftp> cd foo
Can't change directory: Can't check target
```

POSIX permissions are not being returned for these directories, which is causing an exception in the SFTP client when attempting to `cd` to the directory. 

# Tasks

The following tasks will need to be carried out:
* [ ] When getting S3 Posix File Attributes in `S3Utils`, if the path is a directory, obtain the bucket ACL, then obtain its ACL grant permissions, convert them to Posix file permissions and return them with the response.

# Useful Links

* [Upplication/Amazon-S3-FileSystem-NIO2#94](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/issues/94) : Unable to change directories when exposed via Mina SFTP

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov

### PR DESCRIPTION
**Pull request by ptirador**
# Pull Request Description

This pull request closes #146.

# Acceptance Test

* [x] Building the code with `mvn clean install -Pintegration-tests` still works.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [x] Yes, please see [Basic Example](https://s3fs-nio.carlspring.org/reference/examples/basic-example/), [MINA Example](https://s3fs-nio.carlspring.org/reference/examples/mina-example/) and [Spring Example](https://s3fs-nio.carlspring.org/reference/examples/spring-example/).
  * [ ] No

### CODE REVIEW

**Comment by ptirador** [comment]
@carlspring: This is ready for review.

File: src/main/java/org/carlspring/cloud/storage/s3fs/util/S3Utils.java [hunk 1]
```diff
@@ -168,28 +170,35 @@ public S3BasicFileAttributes getS3FileAttributes(S3Path s3Path)
...
-            S3Client client = s3Path.getFileSystem().getClient();
-            GetObjectAclResponse acl = client.getObjectAcl(GetObjectAclRequest.builder().bucket(bucketName).key(key).build());
-            Owner owner = acl.owner();
+            final GetObjectAclRequest request = GetObjectAclRequest.builder().bucket(bucketName).key(key).build();
+            final GetObjectAclResponse acl = client.getObjectAcl(request);
+            owner = acl.owner();
+            permissions = toPosixFilePermissions(acl.grants());
 
-            userPrincipal = new S3UserPrincipal(owner.id() + ":" + owner.displayName());
+        } else {
```
Comment (carlspring) [inline src/main/java/org/carlspring/cloud/storage/s3fs/util/S3Utils.java:193]:
```suggestion
        }
        else
        {
```

**Comment by carlspring** [comment]
Good job! Thanks, @ptirador!
