### PR TITLE
issue-183: Use tags instead of suites to separate tests

### LINKED ISSUE #183: Use tags instead of suites to separate tests
# Task Description

In #140 we introduced the concept of "suites". Unfortunately this doesn't seem to be working very well and the unit tests are not being triggered at all. Furthermore, it has complicated our dependencies since we also need to use `JUnit 4` to run those "suites": 

```
@RunWith(JUnitPlatform.class)
@IncludeTags({ "s3-integration-test" })
@SelectPackages({ "org.carlspring.cloud.storage.s3fs" })
public class AmazonS3ITSuite {}

/** 
 * ......
 * Please note that test classes and suites annotated with
 * @RunWith(JUnitPlatform.class) cannot be executed directly on
 * the JUnit Platform (or as a "JUnit 5" test as documented in some IDEs). Such
 * classes and suites can only be executed using JUnit 4 infrastructure.
 * ......
 */
org.junit.platform.runner.JUnitPlatform 
{
}
```

Since there is no official support for suites yet (junit-team/junit5#744 which is supposed to be fixed via junit-team/junit5#2416), we will have to fall back to simply `@Tag` instead.

# Tasks

The following tasks will need to be carried out:

* [x] Revert changes made via #140.
* [x] Create `MinioIntegrationTest` and `S3IntegrationTest` annotations which can be used per class or method
* [x] Setup proper profiles which run these annotations
* [x] Tag integration tests with the appropriate annotation
* [x] Make sure build actually `fails` when there NO tests run to prevent false-positive green builds
* [x] Run integration tests in GH Actions.
* [x] Change gh issue templates to use `-Pit-s3` instead of `-Pintegration-tests`
* [ ] Change documentation to use `-Pit-s3` instead of `-Pintegration-tests`

# Task Relationships

This task:
* Relates to: #140

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov

### PR DESCRIPTION
**Pull request by steve-todorov**
# Pull Request Description

This pull request closes #183.

It is important to note this pull request has introduced two new profiles - `it-s3` and `it-minio` which are used to trigger tests tagged with `@S3IntegrationTest` and `@MinioIntegrationTest`.

# Acceptance Test

* [x] Building the code with `mvn clean install -Punit-tests,it-minio,it-s3` still works.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see [provide details here]
  * [x] No

### CODE REVIEW

**Comment by steve-todorov** [comment]
Reported bugs were not introduced with this PR but simply reported here because tests are now executing. 
Also, some of the reported new `code smells` are false-positives since it cannot detect the usage.

File: src/main/java/org/carlspring/cloud/storage/s3fs/S3FileStore.java [hunk 1]
```diff
@@ -117,6 +117,12 @@ public Bucket getBucket()
         return getBucket(name);
     }
 
+    /**
+     * This code requires `s3:ListAllMyBuckets` permission.
```
Comment (carlspring) [inline src/main/java/org/carlspring/cloud/storage/s3fs/S3FileStore.java:121]: :+1:

File: src/main/java/org/carlspring/cloud/storage/s3fs/util/S3Utils.java [hunk 2]
```diff
@@ -164,7 +164,8 @@ public S3BasicFileAttributes getS3FileAttributes(S3Path s3Path)
     }
 
     /**
-     * get the S3PosixFileAttributes for a S3Path
+     * Get the S3PosixFileAttributes for a S3Path
+     * This requires `s3:GetBucketAcl` and `s3:GetObjectAcl`
```
Comment (carlspring) [inline src/main/java/org/carlspring/cloud/storage/s3fs/util/S3Utils.java:168]: :+1:

File: pom.xml [hunk 3]
```diff
@@ -287,32 +288,89 @@
...
+                                    <goal>verify</goal>
+                                </goals>
+                            </execution>
+                        </executions>
+                    </plugin>
+                </plugins>
+            </build>
+        </profile>
 
+        <profile>
```
Comment (carlspring) [inline pom.xml:337]: :+1:

**Comment by steve-todorov** [comment]
The failing quality gate is related to decreased code coverage which seems to be because SonarQube is (for some unknown reason) ignoring the integration test reports. We should probably look into it as a follow-up.

File: src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewAsynchronousFileChannelTestIT.java [hunk 4]
```diff
@@ -27,16 +28,15 @@
...
 import org.junit.jupiter.api.Test;
 import static org.carlspring.cloud.storage.s3fs.util.S3EndpointConstant.S3_GLOBAL_URI_IT;
 import static org.junit.jupiter.api.Assertions.assertArrayEquals;
 import static org.junit.jupiter.api.Assertions.assertNotNull;
 import static org.junit.jupiter.api.Assertions.assertThrows;
 import static org.junit.jupiter.api.Assertions.assertTrue;
 
-@Tag("s3-integration-test")
-class NewAsynchronousFileChannelITTest
+@S3IntegrationTest
```
Comment (mslowiak) [inline src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewAsynchronousFileChannelTestIT.java:38]: It extends S3UnitTestBase, shouldn't we skip the `@S3IntegrationTest` annotation in such a case?
On the other hand, if this is an integration test we should skip extending the unit test I think

File: src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewByteChannelIT.java [hunk 5]
```diff
@@ -22,16 +23,15 @@
...
 import org.junit.jupiter.api.Test;
 import static org.carlspring.cloud.storage.s3fs.util.S3EndpointConstant.S3_GLOBAL_URI_IT;
 import static org.junit.jupiter.api.Assertions.assertArrayEquals;
 import static org.junit.jupiter.api.Assertions.assertNotNull;
 import static org.junit.jupiter.api.Assertions.assertThrows;
 import static org.junit.jupiter.api.Assertions.assertTrue;
 
-@Tag("s3-integration-test")
-class NewByteChannelITTest
+@S3IntegrationTest
```
Comment (mslowiak) [inline src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewByteChannelIT.java:33]: Same as https://github.com/carlspring/s3fs-nio/pull/184/files#r564704106

File: src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewAsynchronousFileChannelTestIT.java (hunk 4 above)
Comment (steve-todorov) [reply src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewAsynchronousFileChannelTestIT.java:38]: Indeed it sounds misleading to have `S3UnitTestBase` and `@S3IntegrationTest` at the same time. :)
Unfortunately we inherited a lot of cases like this one from Upplication's fork and we'll have to clear them out in due time. Changing this behavior is out of the scope of this PR. :)

**Comment by carlspring** [comment]
Could you please create a follow-up task for this? Thanks!

**Comment by mslowiak** [comment]
> Could you please create a follow-up task for this? Thanks!

Follow up here:
https://github.com/carlspring/s3fs-nio/issues/187

File: src/main/java/org/carlspring/cloud/storage/s3fs/S3Path.java [hunk 6]
```diff
@@ -64,7 +64,7 @@
      */
     public S3Path(S3FileSystem fileSystem, String first, String... more)
     {
-        Preconditions.checkArgument(first != null, "first path must be not null");
+        Preconditions.checkArgument(first != null, "first path must be not null, maybe you forgot to set the bucket name?");
```
Comment (carlspring) [inline src/main/java/org/carlspring/cloud/storage/s3fs/S3Path.java:67]:
```suggestion
        Preconditions.checkArgument(first != null, "The first path must not be null. Perhaps you forgot to set the bucket name?");
```

File: src/main/java/org/carlspring/cloud/storage/s3fs/S3Path.java [hunk 7]
```diff
@@ -64,7 +64,7 @@
...
         Preconditions.checkArgument(!first.startsWith("//"), "first path doesnt start with '//'. Miss bucket");
```
Comment (carlspring) [inline src/main/java/org/carlspring/cloud/storage/s3fs/S3Path.java:68]:
```suggestion
        Preconditions.checkArgument(!first.startsWith("//"), "The first path doesn't start with '//'. Missing bucket.");
```

File: src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java [hunk 8]
```diff
@@ -32,17 +36,19 @@
...
 
-        if (accessKey != null && secretKey != null && region != null && protocol != null)
+        if (accessKey != null && secretKey != null && region != null && protocol != null && bucket != null)
         {
             env = ImmutableMap.<String, Object>builder().put(ACCESS_KEY, accessKey)
                                            .put(SECRET_KEY, secretKey)
                                            .put(REGION, region)
                                            .put(PROTOCOL, protocol)
+                                           .put(BUCKET_NAME_KEY, bucket)
                                            .build();
```
Comment (carlspring) [inline src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java:52]: If you could just re-align these chained calls, that'll be great! :)

File: src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java [hunk 9]
```diff
@@ -68,14 +74,49 @@
...
+    private static String getS3EnvName(@Nonnull String key)
+    {
+        // Sometimes the key will contain `S3FS_` or `s3fs.property.name` which is why we need to sanitize the string
+        // to ensure consistency.
+        String sanitized = StringUtils.removeStartIgnoreCase(key, "S3FS.");
+        sanitized = StringUtils.removeStartIgnoreCase(sanitized, "S3FS_");
+        sanitized = sanitized.replaceAll("\\.", "_").toUpperCase();
+
+        String integrationSuite = System.getProperty("running.it");
+        if(integrationSuite != null && integrationSuite.equalsIgnoreCase("minio"))
```
Comment (carlspring) [inline src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java:102]:
```suggestion
        if (integrationSuite != null && integrationSuite.equalsIgnoreCase("minio"))
```

Comment (steve-todorov) [reply src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java:102]: ignoring this since this logic will be entirely removed in #186 for now.

File: src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java (hunk 8 above)
Comment (steve-todorov) [reply src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java:52]: fixed

**Review by carlspring — APPROVED** [review]
LGTM! :)
